package com.sample
 
import com.sample.DroolsTest.Message;
 


rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        System.out.println( "rule 1 " );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
    
        System.out.println( "rule 2 " );
        System.out.println( myMessage );
end
